openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Person:
      type: "object"
      required:
        - nome
        - rg
        - cpf
        - data_nascimento
        - data_admissao
      properties:
        nome:
          type: "string"
        rg:
          type: "string"
        cpf:
          type: "string"
        data_nascimento:
          type: "string"
        data_admissao:
          type: "string"

  parameters:
    cpf:
      name: "cpf"
      description: "CPF number of the person to get"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /people:
    get:
      operationId: "people.read_all"
      tags:
        - "People"
      summary: "Read the list of people"
      responses:
        "200":
          description: "Successfully read people list"

    post:
      operationId: "people.create"
      tags:
        - People
      summary: "Create a person"
      requestBody:
          description: "Person to create"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "person"
                $ref: "#/components/schemas/Person"
      responses:
        "201":
          description: "Successfully created person"

  /people/{cpf}:
    get:
      operationId: "people.read_one"
      tags:
        - People
      summary: "Read one person"
      parameters:
        - $ref: "#/components/parameters/cpf"
      responses:
        "200":
          description: "Successfully read person"
